Stage
datajoint/mym pull request #90
Opened 2022-02-25 20:30 UTC by A-Baji

2022-02-28 17:05 UTC, A-Baji commented
The value for the repository secret `MATLAB_LICENSE_R2018B` needs to be updated to the same as `MATLAB_LICENSE_R2019A`.

I think alternatively, dynamically setting the license is unnecessary since the license for R2019A works for both R2018B and R1026B versions, so a single secret `MATLAB_LICENSE` value would work.

2022-03-01 17:59 UTC, guzman-raphael requested changes
@A-Baji Glad to see you helping out with `mYm`! :handshake: Great work!

Could you also update a few more items?
- bump the version in `mym.h`
- update the binaries to reflect these changes for Linux, Windows, and MacOS (see `./mex_compilation`)
- Dimitri had a good [comment](https://github.com/datajoint/mym/pull/89#discussion_r814960636) that I think was missed

2022-03-01 17:59 UTC, guzman-raphael commented on tests/TestExternal.m
> +                unpacked = mym('deserialize', packed);
Could you update your test to verify the contents of the unpacked data?

2022-03-01 17:59 UTC, guzman-raphael commented on tests/TestExternal.m
> +            end
We can remove the `try/catch` here since we are not checking for an explicit error message being thrown.

2022-03-05 14:30 UTC, guzman-raphael requested changes
@A-Baji Think this should satisfy @dimitri-yatsenko's earlier point about simplification.

Also, noticed that we don't have a test to verify the version of the binary. Could you add one in as well? Let's bump it to `2.8.4` to help us easily verify the new binaries.

2022-03-05 14:30 UTC, guzman-raphael commented on src/mym.cpp
> +        return false;
```suggestion
    return getenv("USE_32BIT_DIMS") && strcasecmp(getenv("USE_32BIT_DIMS"), "true") == 0;
```

2022-03-07 17:37 UTC, A-Baji commented
> Also, noticed that we don't have a test to verify the version of the binary. Could you add one in as well?

Could you elaborate on this? Does it have anything to do with the binary version check in the linux docker compose?

2022-03-08 15:20 UTC, guzman-raphael commented
@A-Baji Ah great point! Forgot that we do display the binary version already. That is enough. Think we are all good now and thanks for the updates. I'll try to add binaries for the other OS' around 8AM CST tomorrow. We can merge after that.

2022-03-09 15:01 UTC, guzman-raphael approved these changes

2022-03-09 15:02 UTC, guzman-raphael commented
@A-Baji Excellent work and great to collab with you on this one! :handshake:

2022-03-09 15:02 UTC, merged